/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dmisiuk' at '1/1/16 3:53 PM' with Gradle 2.10
 *
 * @author dmisiuk, @date 1/1/16 3:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
